- name: Pip install pip
  pip: name=pip executable={{ pip_version }} extra_args='--user' state='latest'

- name: Pip in $PATH
  lineinfile:
    dest={{homedir}}/.bashrc
    line="export PATH=~/.local/bin:$PATH"
