- name: Make home bin directory
  file: path={{ homebin }} state=directory

- name: Config git repo script
  template:
    src=config-gitrepo.j2
    dest={{ homebin }}/config-gitrepo mode="u=rwx,g=r,o=r"

- name: Clean build script
  copy:
    src=clean-build.sh
    dest={{ homebin }}/clean-build mode="u=rwx,g=r,o=r"


