- name: Install python 2
  action: apt pkg=python state=latest
  become: yes

- name: Install python 2 dev
  action: apt pkg=python-dev state=latest
  become: yes

- name : Install python2 setuptools
  action: apt pkg=python-setuptools state=latest
  become: yes

- name : Install python2 pip
  action: apt pkg=python-pip state=latest
  become: yes

- name: Install python 3
  action: apt pkg=python3 state=latest
  become: yes

- name: Install python 3 dev
  action: apt pkg=python3-dev state=latest
  become: yes

- name : Install python3 setuptools
  action: apt pkg=python3-setuptools state=latest
  become: yes

- name : Install python3 pip
  action: apt pkg=python3-pip state=latest
  become: yes
