- name: Install tmux (last version)
  become: yes
  action: apt pkg=tmux state=latest
  

- name: Install Tmux plugin manager
  git:
    repo=https://github.com/tmux-plugins/tpm.git
    dest={{homedir}}/.tmux/plugins/tpm

- name: Tmux config file
  template:
    src=roles/tmux/files/tmux.conf
    dest={{homedir}}/.tmux.conf
    backup=yes
