- name: Pip install virtualenv
  pip: name=virtualenv extra_args='--user'

- name: Pip install virtualenvwrapper
  pip: name=virtualenvwrapper extra_args='--user'

- name: virtualenvwrapper directory
  file:
    path=/home/emmanuel/envs state=directory

- name: Virtualenvwrapper directory in bashrc
  lineinfile:
    dest=/home/emmanuel/.bashrc
    line="export WORKON_HOME=$HOME/envs"

- name: Virtualenvwrapper loading in bashrc
  lineinfile:
    dest=/home/emmanuel/.bashrc
    line=". $HOME/.local/bin/virtualenvwrapper.sh"

- name: Virtualenvwrapper postactivate hook
  lineinfile:
    dest=/home/emmanuel/envs/postactivate
    line="cd $VIRTUAL_ENV"
