- name: Pip install virtualenv
  pip: name=virtualenv executable={{ pip_version }} extra_args='--user' state='latest'

- name: Pip install virtualenvwrapper
  pip: name=virtualenvwrapper executable={{ pip_version }} extra_args='--user' state='latest'

- name: Pip install flake8
  pip: name=flake8 executable={{ pip_version }} extra_args='--user' state='latest'

- name: Configuration file for flake8
  copy:
      src=flake8 dest={{ ansible_env.HOME }}/.config/flake8

- name: virtualenvwrapper directory
  file:
    path={{homedir}}/envs state=directory

- name: Virtualenvwrapper directory in bashrc
  lineinfile:
    dest={{homedir}}/.bashrc
    line="export WORKON_HOME=$HOME/envs"

- name: Virtualenvwrapper uses python3
  lineinfile:
    dest={{homedir}}/.bashrc
    line="export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3"

- name: Virtualenvwrapper loading in bashrc
  lineinfile:
    dest={{homedir}}/.bashrc
    line=". $HOME/.local/bin/virtualenvwrapper.sh"

- name: virtualenvwrapper postactivate hook file
  file:
    path={{homedir}}/envs/postactivate
    state=touch

- name: Virtualenvwrapper postactivate hook
  lineinfile:
    dest={{homedir}}/envs/postactivate
    line="cd $VIRTUAL_ENV"
